name: CI

on:
  push:
    branches: [ master, apollo ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Generate Types
      run: |
        ./gradlew downloadApolloSchema \
          -Pcom.apollographql.apollo.endpoint=https://api.github.com/graphql \
          -Pcom.apollographql.apollo.schema=src/main/graphql/com/nevinsjr/rxhubk/schema.json \
          "-Pcom.apollographql.apollo.headers=Authorization=Bearer ${{ secrets.GITHUB_TOKEN }}"

    - name: Build
      run: ./gradlew build
